version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
      - ./backend/app.db:/app/app.db
    depends_on:
      - ml_app
    networks:
      - winkai-net

  ml_app:
    build:
      context: ./ML_app
      dockerfile: Dockerfile
    # Для доступа к GPU, раскомментируйте секцию 'deploy'
    # и убедитесь, что у вас установлен NVIDIA Container Toolkit.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - winkai-net

networks:
  winkai-net:
    driver: bridge