version: '3.8'
services:
  winkai:
    build: .
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
    depends_on:
      - ml_app

  ml_app:
    build:
      context: ./ML_app
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - winkai
